# This is a basic workflow to help you get started with Actions

name: Collect

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 */3 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.12
      - name: Install dependencies
        run: pip3 install selenium pymongo 'pymongo[srv]'
      - name: Collecting Game Boy
        run: |
          python3 collector.py game-boy.json
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
      - name: Collecting Game Boy Color
        run: |
          python3 collector.py game-boy-color.json
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
      - name: Collecting Dreamcast
        run: |
          python3 collector.py dc.json
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
      - name: Collecting MegaDrive
        run: |
          python3 collector.py mega-drive.json
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
      - name: Collecting NES
        run: |
          python3 collector.py nes.json
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
      - name: Collecting SNES
        run: |
          python3 collector.py snes.json
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
      - name: Collecting PlayStation
        run: |
          python3 collector.py ps1.json
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
      - name: Collecting PlayStation 2
        run: |
          python3 collector.py ps2.json
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
