# This is a basic workflow to help you get started with Actions

name: Collect

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 */1 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gb:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.12
      - name: Install dependencies
        run: pip3 install selenium pymongo 'pymongo[srv]'
      - name: Collecting Game Boy
        continue-on-error: true
        run: |
          python3 collector.py game-boy.json
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
  gbc:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.12
      - name: Install dependencies
        run: pip3 install selenium pymongo 'pymongo[srv]'
      - name: Collecting Game Boy Color
        continue-on-error: true
        run: |
          python3 collector.py game-boy-color.json
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
  dc:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.12
      - name: Install dependencies
        run: pip3 install selenium pymongo 'pymongo[srv]'
      - name: Collecting Dreamcast
        continue-on-error: true
        run: |
          python3 collector.py dc.json
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
  md:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.12
      - name: Install dependencies
        run: pip3 install selenium pymongo 'pymongo[srv]'
      - name: Collecting MegaDrive
        continue-on-error: true
        run: |
          python3 collector.py mega-drive.json
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
  nes:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.12
      - name: Install dependencies
        run: pip3 install selenium pymongo 'pymongo[srv]'
      - name: Collecting NES
        continue-on-error: true
        run: |
          python3 collector.py nes.json
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
  snes:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.12
      - name: Install dependencies
        run: pip3 install selenium pymongo 'pymongo[srv]'
      - name: Collecting SNES
        continue-on-error: true
        run: |
          python3 collector.py snes.json
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
  ps1:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.12
      - name: Install dependencies
        run: pip3 install selenium pymongo 'pymongo[srv]'
      - name: Collecting PlayStation
        continue-on-error: true
        run: |
          python3 collector.py ps1.json
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
  ps2:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.12
      - name: Install dependencies
        run: pip3 install selenium pymongo 'pymongo[srv]'
      - name: Collecting PlayStation 2
        continue-on-error: true
        run: |
          python3 collector.py ps2.json
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
