# This is a basic workflow to help you get started with Actions

name: Process

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 */6 * * *"

jobs:
  processN:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.12
      - name: Install dependencies
        run: pip3 install pymongo 'pymongo[srv]' statistics scipy datetime numpy
      - name: Process
        run: |
          python3 processor.py 'Game Boy','Game Boy Color','SNES','NES'
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
  processS:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.12
      - name: Install dependencies
        run: pip3 install pymongo 'pymongo[srv]' statistics scipy datetime numpy
      - name: Process
        run: |
          python3 processor.py "SEGA MegaDrive","SEGA Dreamcast"
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
  processP:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.12
      - name: Install dependencies
        run: pip3 install pymongo 'pymongo[srv]' statistics scipy datetime numpy
      - name: Process
        run: |
          python3 processor.py "PlayStation 1","PlayStation 2"
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
